version: '3.8'
services:
  config-service:
    build: ./config-service
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-service:
    build: ./eureka-service
    ports:
      - "8761:8761"
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  iam-db:
    image: mysql:8
    container_name: iam-db
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=iamdb
    volumes:
      - iam-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 5

  appointment-db:
    image: mysql:8
    container_name: appointment-db
    ports:
      - "33062:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=appointmentdb
    volumes:
      - appointment-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 5

  management-db:
    image: mysql:8
    container_name: management-db
    ports:
      - "33063:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=managementdb
    volumes:
      - management-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 5

  post-db:
    image: mysql:8
    container_name: post-db
    ports:
      - "33064:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=postdb
    volumes:
      - post-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 5

  profile-db:
    image: mysql:8
    container_name: profile-db
    ports:
      - "33065:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=profiledb
    volumes:
      - profile-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 5

  iam-service:
    build: ./iam-service
    ports:
      - "8094:8094"
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
      iam-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8094/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - authorization.jwt.secret=${JWT_SECRET}
      - authorization.jwt.expiration.days=${JWT_EXPIRATION_DAYS}

  profile-service:
    build: ./profile-service
    ports:
      - "8093:8093"
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
      iam-service:
        condition: service_healthy
      profile-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8093/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - authorization.jwt.secret=${JWT_SECRET}
      - authorization.jwt.expiration.days=${JWT_EXPIRATION_DAYS}

  appointment-service:
    build: ./appointment-service
    ports:
      - "8090:8090"
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
      profile-service:
        condition: service_healthy
      appointment-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - authorization.jwt.secret=${JWT_SECRET}
      - authorization.jwt.expiration.days=${JWT_EXPIRATION_DAYS}

  management-service:
    build: ./management-service
    ports:
      - "8081:8081"
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
      profile-service:
        condition: service_healthy
      management-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - authorization.jwt.secret=${JWT_SECRET}
      - authorization.jwt.expiration.days=${JWT_EXPIRATION_DAYS}

  post-service:
    build: ./post-service
    ports:
      - "8092:8092"
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
      profile-service:
        condition: service_healthy
      post-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - authorization.jwt.secret=${JWT_SECRET}
      - authorization.jwt.expiration.days=${JWT_EXPIRATION_DAYS}

volumes:
  iam-db-data:
  appointment-db-data:
  management-db-data:
  post-db-data:
  profile-db-data:
