server:
  port: 8081

spring:
  security:
    user:
      name: admin
      password: 12345678
      roles: ADMIN,USER
  config:
    import: configserver:http://localhost:8888
  application:
    name: management-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/managementdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.agrotech.management.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    status-page-url-path: /swagger-ui/index.html

profiles:
  api:
    url: http://localhost:8093  # El puerto 8093 es el puerto del microservicio de perfil