server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  config:
    import: configserver:http://config-service:8888
  application:
    name: appointment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://appointment-db:3306/appointmentdb?allowPublicKeyRetrieval=true&useSSL=false # el db es unico por microservicio
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.agrotech.appointment.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
authorization:
  jwt:
    secret: ${JWT_SECRET}
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    status-page-url-path: /swagger-ui/index.html
profiles:
  api:
    url: http://gateway-service:8080