server:
  port: 8090

spring:
  application:
    name: appointment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appointmentdb?allowPublicKeyRetrieval=true&useSSL=false # el db es unico por microservicio
    username: root
    password: 123456789
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.agrotech.appointment.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
profiles:
  api:
    url: http://localhost:8093  # El puerto 8093 es el puerto del microservicio de perfil