server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FarmWise-UPC/Microservices-config